<?php

/**
 * ASE Makine product catalog — data extracted from ASE Makine Katalog PDF.
 * Categories and product names in Greek to match the catalog.
 */

return [
    'catalog_pdf' => 'ASE Makine Katalog.pdf',
    'images_dir' => 'img/ase/pages',
    'slug_to_pdf_page' => [
        'hsp-em' => 2, 'hsp-dm' => 2,
        'vp-500-tmk-dhs' => 3, 'vp-500-tmk' => 3,
        'vp-500-dhl' => 4, 'vp-500-ehl' => 4, 'vp-500-tmk-ehl' => 4, 'vp-500-tmk-dhl' => 4,
        'sivajet-mn' => 5,
        'sm-5-standard' => 6, 'sm-5-mn' => 7, 'sm-5-mt' => 7, 'sm-5-plus' => 8, 'sm-5-premium' => 8,
        'duojet' => 9, 'duojet-fc' => 9,
        'universal' => 10, 'universal-fc' => 10, 'universal-75' => 11, 'universal-75-fc' => 11,
        'hvp-18' => 12, 'evp-18' => 12,
        'vp-210' => 13, 'vp-210-k-fc' => 13,
        'vp-250' => 14, 'vp-250-k-fc' => 14,
        'vp-500' => 15, 'vp-500-k-fc' => 15,
        'shm-25' => 16, 'shm-25-mn' => 16,
        'mix-15' => 17,
        'evp-18-s' => 18, 'hvp-18-s' => 18,
        'tks' => 19,
        'fpm-25' => 20, 'fpm-25-fc' => 20, 'fpm-35-fc' => 21, 'fpm-35-dh' => 21,
        'grc-200-fc' => 22, 'grc-mix-3' => 23, 'grc-mix-5-fc' => 23,
        'tem-250' => 24, 'tem-250-fc' => 24,
        'dep-200' => 25, 'dep-200-fc' => 25,
        'gp-50-m' => 26,
        'alp-130' => 27,
    ],
    'categories' => [
        'piston' => 'Αντλίες εμβόλου για σκόνη και γόβα',
        'traditional' => 'Παραδοσιακές αντλίες γόβας',
        'mixing' => 'Αντλίες ανάμειξης',
        'ready_mix' => 'Αντλίες έτοιμου κονιάματος',
        'wet_screed' => 'Αντλίες έτοιμου αναμειξής για υγρό κονιαματόδεσμο',
        'transfer' => 'Αντλίες μεταφοράς κονιαμάτων',
        'continuous_mixer' => 'Συνέχεις μιξερ',
        'mortar_mixer' => 'Μιξερ κονιαμάτων',
        'wet_shotcrete' => 'Αντλίες υγρού σκονήματος',
        'dry_shotcrete' => 'Μηχανήματα ξηρού σκονήματος',
        'fireproof' => 'Πυροαντιπαρασκευαστικές αντλίες',
        'grc' => 'Μίξερ GRC',
        'injection' => 'Αντλίες εγχύσης κονιαμάτων',
        'grouting' => 'Αντλίες αρμολόγησης',
        'airless' => 'Αντλίες ψεκασμού υψηλής πίεσης χωρίς αέρα',
    ],
    'products' => [
        ['slug' => 'hsp-em', 'name' => 'ASE HSP/EM', 'category' => 'piston', 'short' => 'Ηλεκτρική αντλία διπλού εμβόλου υψηλής πίεσης με ανυψωτικό αναμικτήρα.'],
        ['slug' => 'hsp-dm', 'name' => 'ASE HSP/DM', 'category' => 'piston', 'short' => 'Αντλία διπλού εμβόλου με ντίζελ και ανυψωτικό αναμικτήρα.'],
        ['slug' => 'vp-500-tmk-dhs', 'name' => 'ASE VP 500 TMK/DHS', 'category' => 'traditional', 'short' => 'Παραδοσιακή αντλία γόβας ντίζελ με υδραυλικό κινητήρα και ανατρεπόμενο αναδευτήρα.'],
        ['slug' => 'vp-500-tmk', 'name' => 'ASE VP 500 TMK', 'category' => 'traditional', 'short' => 'Ηλεκτρική παραδοσιακή αντλία γόβας με ανατρεπόμενο αναδευτήρα.'],
        ['slug' => 'vp-500-dhl', 'name' => 'ASE VP 500 DHL', 'category' => 'traditional', 'short' => 'Ντίζελ με υδραυλικό κινητήρα και ανυψωτικό αναδευτήρα.'],
        ['slug' => 'vp-500-ehl', 'name' => 'ASE VP 500 EHL', 'category' => 'traditional', 'short' => 'Ηλεκτρική αντλία με ανυψωτικό αναδευτήρα.'],
        ['slug' => 'vp-500-tmk-ehl', 'name' => 'ASE VP 500 TMK/EHL', 'category' => 'traditional', 'short' => 'Ηλεκτρικό μοντέλο με αναδευτήρα κλίσης.'],
        ['slug' => 'vp-500-tmk-dhl', 'name' => 'ASE VP 500 TMK/DHL', 'category' => 'traditional', 'short' => 'Ντίζελ με αναδευτήρα κλίσης.'],
        ['slug' => 'sivajet-mn', 'name' => 'ASE SIVAJET MN', 'category' => 'mixing', 'short' => 'Μικρό μηχάνημα έτοιμου σοβά, λειτουργία 230V.'],
        ['slug' => 'sm-5-standard', 'name' => 'ASE SM 5 STANDART', 'category' => 'mixing', 'short' => 'Μηχανή σοβατίσματος έτοιμου μείγματος ανώτερης απόδοσης.'],
        ['slug' => 'sm-5-mn', 'name' => 'ASE SM 5 MN', 'category' => 'mixing', 'short' => 'Ίδιο με SM 5, λειτουργία 220V.'],
        ['slug' => 'sm-5-mt', 'name' => 'ASE SM 5 MT', 'category' => 'mixing', 'short' => 'Υποστήριξη 220V και 380V.'],
        ['slug' => 'sm-5-plus', 'name' => 'ASE SM 5 PLUS', 'category' => 'mixing', 'short' => 'Έκδοση Plus με βελτιωμένα χαρακτηριστικά.'],
        ['slug' => 'sm-5-premium', 'name' => 'ASE SM 5 PREMIUM', 'category' => 'mixing', 'short' => 'Έκδοση Premium.'],
        ['slug' => 'duojet', 'name' => 'ASE DUOJET', 'category' => 'ready_mix', 'short' => 'Κινητή αντλία έτοιμου κονιάματος με συνεχή αναμικτήρα και αντλία κοχλία.'],
        ['slug' => 'duojet-fc', 'name' => 'ASE DUOJET FC', 'category' => 'ready_mix', 'short' => 'DUOJET με μετατροπέα συχνότητας για ρύθμιση ικανότητας άντλησης.'],
        ['slug' => 'universal', 'name' => 'ASE UNIVERSAL', 'category' => 'ready_mix', 'short' => 'Ιδανικό για εφαρμογές πολυσυστατικών κονιαμάτων με ξεχωριστή μονάδα ανάμειξης.'],
        ['slug' => 'universal-fc', 'name' => 'ASE UNIVERSAL FC', 'category' => 'ready_mix', 'short' => 'UNIVERSAL με μετατροπέα συχνότητας.'],
        ['slug' => 'universal-75', 'name' => 'ASE UNIVERSAL 75', 'category' => 'ready_mix', 'short' => 'Μεγαλύτερη χωρητικότητα χοάνης ανάμειξης.'],
        ['slug' => 'universal-75-fc', 'name' => 'ASE UNIVERSAL 75 FC', 'category' => 'ready_mix', 'short' => 'UNIVERSAL 75 με ρύθμιση άντλησης.'],
        ['slug' => 'hvp-18', 'name' => 'ASE HVP 18', 'category' => 'wet_screed', 'short' => 'Αντλία έτοιμου υγρού κονιάματος/ελαφρού σκυροδέματος, ντίζελ, έως 18 m³/h.'],
        ['slug' => 'evp-18', 'name' => 'ASE EVP 18', 'category' => 'wet_screed', 'short' => 'Ηλεκτρική έκδοση, ρύθμιση άντλησης με μετατροπέα συχνότητας.'],
        ['slug' => 'vp-210', 'name' => 'ASE VP 210', 'category' => 'transfer', 'short' => 'Ηλεκτροκίνητη βιδωτή μίνι αντλία, ελαφριά και αρθρωτή.'],
        ['slug' => 'vp-210-k-fc', 'name' => 'ASE VP 210 K/FC', 'category' => 'transfer', 'short' => 'VP 210 με ενσωματωμένο συμπιεστή και ρύθμιση FC.'],
        ['slug' => 'vp-250', 'name' => 'ASE VP 250', 'category' => 'transfer', 'short' => 'Συμπαγής βιδωτή αντλία midi, υψηλή ικανότητα άντλησης.'],
        ['slug' => 'vp-250-k-fc', 'name' => 'ASE VP 250 K/FC', 'category' => 'transfer', 'short' => 'VP 250 με συμπιεστή και ψεκασμό.'],
        ['slug' => 'vp-500', 'name' => 'ASE VP 500', 'category' => 'transfer', 'short' => 'Ηλεκτρική αντλία κοχλία για μεταφορά σε υψηλότερα και μακρινά σημεία.'],
        ['slug' => 'vp-500-k-fc', 'name' => 'ASE VP 500 K/FC', 'category' => 'transfer', 'short' => 'VP 500 με ενσωματωμένο συμπιεστή και ρύθμιση FC.'],
        ['slug' => 'shm-25', 'name' => 'ASE SHM 25', 'category' => 'continuous_mixer', 'short' => 'Οριζόντιος αναμικτήρας συνεχούς κονιάματος, τροφοδοσία από τσάντα ή σιλό.'],
        ['slug' => 'shm-25-mn', 'name' => 'ASE SHM 25 MN', 'category' => 'continuous_mixer', 'short' => 'SHM 25 με λειτουργία 230V.'],
        ['slug' => 'mix-15', 'name' => 'ASE MIX 15', 'category' => 'mortar_mixer', 'short' => 'Μιξερ για ειδικά υλικά, αρμόστικοι, πυρίμαχα, τοιχοποιία.'],
        ['slug' => 'evp-18-s', 'name' => 'ASE EVP 18 S', 'category' => 'wet_shotcrete', 'short' => 'Σύστημα για υγρό εκτοξευόμενο σκυρόδεμα, αμάξωμα ρυμουλκούμενου.'],
        ['slug' => 'hvp-18-s', 'name' => 'ASE HVP 18 S', 'category' => 'wet_shotcrete', 'short' => 'Ίδιο σύστημα με κινητήρα ντίζελ.'],
        ['slug' => 'tks', 'name' => 'ASE TKS', 'category' => 'dry_shotcrete', 'short' => 'Αντλία ψεκασμού ξηρών μιγμάτων, κόκκων έως 20 mm. Σήραγγες, φράγματα, οδοποιία.'],
        ['slug' => 'fpm-25', 'name' => 'ASE FPM 25', 'category' => 'fireproof', 'short' => 'Αντλία κοχλία για ψεκασμό πυρασφάλειας, συμπαγές μοντέλο.'],
        ['slug' => 'fpm-25-fc', 'name' => 'ASE FPM 25 FC', 'category' => 'fireproof', 'short' => 'FPM 25 με μετατροπέα συχνότητας.'],
        ['slug' => 'fpm-35-fc', 'name' => 'ASE FPM 35 FC', 'category' => 'fireproof', 'short' => 'Μεγαλύτερη χωρητικότητα για πυρίμαχα υλικά.'],
        ['slug' => 'fpm-35-dh', 'name' => 'ASE FPM 35 DH', 'category' => 'fireproof', 'short' => 'FPM 35 με κινητήρα ντίζελ.'],
        ['slug' => 'grc-mix-3', 'name' => 'ASE GRC MIX 3', 'category' => 'grc', 'short' => 'Μίξερ για υλικά GRC με βάση τσιμέντο.'],
        ['slug' => 'grc-mix-5-fc', 'name' => 'ASE GRC MIX 5 FC', 'category' => 'grc', 'short' => 'GRC μίξερ με ρύθμιση FC.'],
        ['slug' => 'grc-200-fc', 'name' => 'ASE GRC 200 FC', 'category' => 'grc', 'short' => 'Μοντέλο GRC 200 με μετατροπέα συχνότητας.'],
        ['slug' => 'tem-250', 'name' => 'ASE TEM 250', 'category' => 'injection', 'short' => 'Προαναμεμιγμένη αντλία κοχλία για εφαρμογές εγχύσης ενέματος.'],
        ['slug' => 'tem-250-fc', 'name' => 'ASE TEM 250 FC', 'category' => 'injection', 'short' => 'TEM 250 με ρύθμιση άντλησης.'],
        ['slug' => 'dep-200', 'name' => 'ASE DEP 200', 'category' => 'grouting', 'short' => 'Αντλία ρότορα-στάτορα για αρμολόγηση και έγχυση ενέματος.'],
        ['slug' => 'dep-200-fc', 'name' => 'ASE DEP 200 FC', 'category' => 'grouting', 'short' => 'DEP 200 με μετατροπέα συχνότητας.'],
        ['slug' => 'gp-50-m', 'name' => 'ASE GP 50 M', 'category' => 'grouting', 'short' => 'Φορητή χειροκίνητη παλμική αντλία εμβόλου για ενέματα.'],
        ['slug' => 'alp-130', 'name' => 'ASE ALP 130', 'category' => 'airless', 'short' => 'Ογκομετρική αντλία χωρίς αέρα για ψεκασμό υψηλής πίεσης.'],
    ],
];
